---
title: "R Notebook"
output: html_notebook
---

Arrange figures


Figure 4
```{r}
Fig4a <- readRDS("Figures/R_plots/Figure4a.RDS")
Fig4b <- readRDS("Figures/R_plots/Figure4b.RDS")
Fig4c <- readRDS("Figures/R_plots/Figure4c.RDS") + theme(axis.title.y = element_blank())

png("Figures/Figure4.png", width = 1060, height = 1060)
ggpubr::ggarrange(ggplotify::as.ggplot(Fig4a), NULL,
                  ggpubr::ggarrange(Fig4b, NULL, Fig4c, nrow=3, heights = c(1.6,0.05,2), labels=c("", "", "C"), font.label = list(size = 22, face="bold")), 
                  ncol=3, widths=c(1.3, 0.05, 2.2), labels=c("A", "", "B"), font.label = list(size = 22, face="bold"))
dev.off()
```

Figure 5 (manually arrange 5A) -- add as NULL
```{r}
Fig5b <- readRDS("Figures/R_plots/Figure5b.RDS")

png("Figures/Figure5.png", width = 800, height = 1200)
ggpubr::ggarrange(NULL, Fig5b, nrow=2, labels=c("A", "B"), font.label=list(size=22, face="bold"), 
                  heights=c(0.85, 1), label.y=c(1,1.05))
dev.off()
```


